engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  pep8:
    enabled: true
  radon: 
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true

ratings:
  paths:
    - "**.py"
    - "**.sh"
    - "benchflow"
    - "Dockerfile"
    - "Dockerfile.test"
    - "Dockerfile.ci"

exclude_paths:
- "/test/**/*"
