sudo: required
dist: trusty
group: edge

language: bash

# whitelist

branches:
  only:
    - dev
  except:
    - v-dev

before_install:
  - docker build -f ./test/Dockerfile.ci -t sparktests .
  - wget https://raw.githubusercontent.com/benchflow/docker-images/dev/cassandra/data/benchflow.cql -O ./test/data/benchflow.cql

script:
  - docker run --name minio -e "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE" -e "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" -d benchflow/minio:dev /data
  - sleep 60
  - docker cp ./test/data/runs minio:/data/runs
  - docker run -d --name cassandra cassandra:3.0
  - sleep 60
  - docker run -d --name cassandra2 --link cassandra:cassandra cassandra:3.0
  - sleep 60
  - docker cp ./test/data/benchflow.cql cassandra:/
  - docker exec cassandra cqlsh -f /benchflow.cql
  - travis_wait 30 docker run --rm --name spark --link minio:minio --link cassandra:cassandra --entrypoint=/test/runTests.sh sparktests

after_success:
  # Clean the v-dev release and tag we are using to release development version in CI
  - sudo wget https://github.com/benchflow/devops/raw/dev/ci/clean_v-dev_release.sh -O /usr/bin/clean_v-dev_release.sh
  - sudo chmod +x /usr/bin/clean_v-dev_release.sh
  - export REPO_NAME=data-transformers
  - /usr/bin/clean_v-dev_release.sh